name: gl-native-node Linux Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64]
        target-os: [linux]

    steps:
      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'mhalada/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node

      - name: Checkout libimagequant dependency
        uses: actions/checkout@v4
        with:
            repository: 'ImageOptim/libimagequant'
            ref: '2.17.0'
            path: gl-native-node/vendor/libimagequant

      - name: Checkout mapbox-gl-native dependency
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/mapbox-gl-native-private'
            ref: 'maptiler'
            path: gl-native-node/vendor/mapbox-gl-native
            token: ${{ secrets.GH_PAT }}
            submodules: 'recursive'

      - name: Download libwebp dependency
        working-directory: gl-native-node
        run: |
          mkdir dist
          wget https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.0-linux-x86-64.tar.gz
          tar -xvzf libwebp-1.3.0-linux-x86-64.tar.gz
          cp libwebp-1.3.0-linux-x86-64/lib/libwebp.a dist/.

      - name: Download ANGLE dependency
        working-directory: gl-native-node
        run: |
          wget https://github.com/mhalada/angle-builds/releases/download/v0.0.1/angle-x64-linux.zip
          unzip angle-x64-linux.zip -d angle-x64-linux
          cp angle-x64-linux/libEGL.so dist/.
          cp angle-x64-linux/libGLESv2.so dist/.
          cp angle-x64-linux/libvk_swiftshader.so dist/.
          cp angle-x64-linux/libvulkan.so.1 dist/.

      - name: Build gl-native-node
        working-directory: gl-native-node
        run: |
          chmod +x ./build.sh
          ./build.sh server

      - name: Artifact Preparation
        working-directory: gl-native-node
        run: |
          cp dist/mbgl-linux-x64.node output/mbgl-linux-x64.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
