name: gl-native-node MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target-cpu == 'arm64' && 'macos-14' || 'macos-13' }}

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Setup Node 14
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Checkout gl-native-node
        uses: actions/checkout@v4
        with:
            repository: 'mhalada/gl-native-node'
            token: ${{ secrets.GH_PAT }}
            path: gl-native-node

      - name: Checkout libimagequant dependency
        uses: actions/checkout@v4
        with:
            repository: 'ImageOptim/libimagequant'
            ref: '2.17.0'
            path: gl-native-node/vendor/libimagequant

      - name: Checkout libwebp dependency
        uses: actions/checkout@v4
        with:
            repository: 'webmproject/libwebp'
            ref: '1.3.0'
            path: gl-native-node/vendor/libwebp

      - name: Checkout mapbox-gl-native dependency
        uses: actions/checkout@v4
        with:
            repository: 'maptiler/mapbox-gl-native-private'
            ref: 'maptiler'
            path: gl-native-node/vendor/mapbox-gl-native
            token: ${{ secrets.GH_PAT }}
            submodules: 'recursive'

      - name: Download ANGLE dependency
        working-directory: gl-native-node
        run: |
          mkdir dist
          wget https://github.com/mhalada/angle-builds/releases/download/v0.0.1/angle-${{ matrix.target-cpu }}-macos.zip -O angle.zip
          unzip angle.zip -d angle
          cp angle/libEGL.dylib dist/.
          cp angle/libGLESv2.dylib dist/.

      - name: Build gl-native-node
        working-directory: gl-native-node
        run: |
          npm install -g cmake-js node-addon-api
          chmod +x ./build.sh
          chmod +x ./build-webp.sh
          ./build-webp.sh
          ./build.sh server

      - name: Artifact Preparation
        working-directory: gl-native-node
        run: |
          mkdir ../output
          cp dist/mbgl-server.node ../output/mbgl-macos-${{ matrix.target-cpu }}.node
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gl-native-node-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
