name: Linux Build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Chromium Branch Number to Build
        type: string
        required: true
        default: '6367'

env:
  ANGLE_BUILDER_OUTPUT_FOLDER: ./angle-builder-output

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [linux]

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Download Depot Tools
        run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - name: Prepend Depot Tools to PATH
        working-directory: depot_tools
        run: echo "$(pwd)" >> $GITHUB_PATH

      - name: Create ANGLE Directory
        run: mkdir angle
      - name: Fetch ANGLE
        working-directory: angle
        run: fetch angle
      - name: Checkout ANGLE Branch
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.branch != 'main' }}
        working-directory: angle
        run: git checkout origin/chromium/${{ inputs.branch }}
      - name: Sync ANGLE
        working-directory: angle
        run: gclient sync
      - name: Configure ANGLE
        env:
          ANGLE_TARGET_CPU: ${{ matrix.target-cpu }}
          ANGLE_TARGET_OS: ${{ matrix.target-os }}
        working-directory: angle
        run: gn gen out/Release --args="target_cpu=\"$ANGLE_TARGET_CPU\" target_os=\"$ANGLE_TARGET_OS\" is_debug=false is_component_build=false"

      - name: Build
        working-directory: angle
        run: autoninja -C out/Release
      - name: Artifact Preparation
        run: |
          mkdir output
          copy -a angle/out/Release/. output/
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: angle-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
