name: swiftshader MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.target-cpu == 'arm64' && 'macos-14' || 'macos-13' }}

    strategy:
      fail-fast: false
      matrix:
        target-cpu: [x64, arm64]
        target-os: [macos]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout swiftshader
        uses: actions/checkout@v4
        with:
            repository: 'google/swiftshader'
            path: swiftshader
            ref: edeff1f2e7dbc2f6e04b1022f84959b584e4e740

      - name: Build swiftshader
        run: |
          chmod +x ./build-swiftshader.sh
          ./build-swiftshader.sh

      - name: Artifact Preparation
        working-directory: swiftshader
        run: |
          ls -R .
          mkdir ../output
          cp build/Darwin/libEGL_deprecated.dylib ../output/libEGL.dylib
          cp build/Darwin/libGLESv2_deprecated.dylib ../output/libGLESv2.dylib
          cp build/Darwin/libvk_swiftshader.dylib ../output/libvk_swiftshader.dylib
          cp build/Darwin/libvulkan.dylib ../output/libvulkan.dylib
          cp build/Darwin/vk_swiftshader_icd.json ../output/vk_swiftshader_icd.json
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftshader-${{ matrix.target-cpu }}-${{ matrix.target-os }}
          path: output/
          retention-days: 1
